### Geek for Geeks Numpy Exercises:
https://www.geeksforgeeks.org/python/pandas-and-numpy-exercies-for-data-analysis/

In [4]:
# create an empty array of shape (3,4)
# The values in the array will be uninitialized and may contain random data
import numpy as np
empty_array = np.empty((3,4))
empty_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# create a full array of shape (3,4) filled with the value 7
full_array = np.full((3,4), 7)
full_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
# create an array of shape (3,4) filled with zeroes
# The dtype argument specifies the data type of the elements in the array, in this case, we want integers. Default is float.
zeroes_arr = np.zeros((3,4), dtype=int)
zeroes_arr


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# create an array of shape (4) filled with ones
ones_arr = np.ones((4))
ones_arr

array([1., 1., 1., 1.])

In [ ]:
# to check if a list is present in the array, we can convert the array to a list of lists using the tolist() method 
# and then check for the presence of the list using the in operator.

import numpy as np
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print("Array:\n", arr)
print([1, 2, 3, 4, 5] in arr.tolist())  
print([1, 2, 3] in arr.tolist())     
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())    
print([11, 12, 13, 14, 15] in arr.tolist())

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
False
True
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
